Docker images improvement
schickling/dockerfiles pull request #145
Opened 2022-04-24 06:43 UTC by jdecool

Related to #144

This PR add a `Makefile` to build all image with the `arm` compatibility.
All image are compatible except the `jekyll` image (it requires `therubyracer` dependency which need to install `v8` which is not compatible with arm architecture).

When I've tested the `Makefile`, I've notice a lot of image build are broken.
So I fix them.

2022-05-01 15:21 UTC, iloveitaly requested changes
I've used this script to update `mysql-backup-s3` and `postgres-backup-s3`. These are the only two containers I have access to on docker hub at the moment. 

I'm going to request the rest and push those in before pushing these in.

2022-05-01 15:21 UTC, iloveitaly commented on Makefile
> +	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n\nTargets:\n"} /^[a-zA-Z_-]+:.*?##/ { printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2 }' $(MAKEFILE_LIST)
This doesn't seem to list out all options available in the makefile

2022-05-01 15:21 UTC, iloveitaly commented on Makefile
> +		--push \
A future improvement here would be to version the containers we push to docker hub. Any ideas on how we might do that?

2022-05-01 16:48 UTC, jdecool commented on Makefile
> +	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n\nTargets:\n"} /^[a-zA-Z_-]+:.*?##/ { printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2 }' $(MAKEFILE_LIST)
What options missing ?

It list only options which have a comment with double `#`.
It seems that only the `help` target isn't list, but it's the default target.

2022-05-01 16:57 UTC, jdecool commented on Makefile
> +		--push \
I've just push a new commit that allow to specify the tag.

How would you specify the tag to apply ? An environment variable ?

2022-05-03 03:07 UTC, iloveitaly commented on Makefile
> +	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n\nTargets:\n"} /^[a-zA-Z_-]+:.*?##/ { printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2 }' $(MAKEFILE_LIST)
s3cmd isn't showing up for me https://github.com/schickling/dockerfiles/tree/master/s3cmd

2022-05-03 03:10 UTC, iloveitaly commented on Makefile
> +		--push \
Nice! Thank you. What do you think would be best?

I'd rather not use an environment variable and do something dynamic instead which the maintainer doesn't need to worry about. Are there any other projects with a similar problem that we can pattern off of?

2022-05-03 19:03 UTC, jdecool commented on Makefile
> +	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n\nTargets:\n"} /^[a-zA-Z_-]+:.*?##/ { printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2 }' $(MAKEFILE_LIST)
Yeah you're right !

I've just pushed a fix for that.

2022-05-03 19:23 UTC, jdecool commented on Makefile
> +		--push \
Environment variable is the easiest way to pass arguments to the `Makefile`.

We can associate each Docker image to a dedicated environment variable contains the tag.

Some examples:

```bash
$ BEANSTALK_TAG="1.0-alpine" make beanstalk
...
$ HUGIN_TAG="2.4-buster" make hugin
```

2022-05-05 00:39 UTC, iloveitaly commented on Makefile
> +		--push \
What if we did something like this?

https://stackoverflow.com/a/36242746/129415

This would eliminate the need to manage which version we should push from the developer. Pretty sure we could automate docker hub updates via GH workflows as a next step as well.

What do you think?

2022-05-05 05:45 UTC, jdecool commented on Makefile
> +		--push \
It's a great idea 👍🏼

2022-05-06 20:53 UTC, jdecool commented on Makefile
> +		--push \
I've just pushed a new commit (161fa0e3481e652a62f0cbf252d8759d6ec71101)

Now, the makefile will detect the tag automatically.
First it will check for `GITHUB_REF` environment variable. This is the variable given by Github Action when execute a workflow. It will contain the tag name if a tag has triggered the job.

If not exists, it will get the current git branch name as tag name.

And finally if the git branch cannot be determinate (because we are on a detached commit), it will take the current short commit has.

2022-05-07 21:16 UTC, iloveitaly commented on Makefile
> +		--push \
Perfect! Sounds like a great idea.

2022-05-07 21:16 UTC, iloveitaly approved these changes

2022-05-07 21:16 UTC, merged